version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123PWD
      - POSTGRES_DB=test
    ports:
      - '${DATABASE_PORT:-54321}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '${REDIS_PORT:-6379}:6379'
volumes:
  pgdata: {}
